@startuml SERP_ERD_Optimized

entity "User" as user {
    + id: number <<PK>>
    --
    fullName: string
    email: string <<unique>>
    password: string
    createdAt: datetime
    updatedAt: datetime
}

entity "Todolist" as todolist {
    + id: number <<PK>>
    --
    name: string
    startDate: datetime
    endDate: datetime
    --
    createdAt: datetime
    updatedAt: datetime
}

entity "UserTodolist" as user_todolist {
    + id: number <<PK>>
    --
    # userId: number <<FK>>
    # todolistId: number <<FK>>
    --
    role: string
    --
    createdBy: number
    updatedBy: number
    createdAt: datetime
    updatedAt: datetime
}

entity "Todo" as todo {
    + id: number <<PK>>
    --
    # todolistId: number <<FK>>
    # parentTodoId: number <<FK>>
    --
    name: string
    completed: boolean
    startDate: datetime 
    dueDate: datetime
    completedDate: datetime
    --
    createdBy: number
    updatedBy: number
    createdAt: datetime
    updatedAt: datetime
}

' Relationships
user ||--o{ todolist: createBy, updateBy
user ||--o{ user_todolist: assigned roles
user ||--o{ todo: assigned tasks

todolist ||--o{ todo: contains
todolist ||--o{ user_todolist: todolists roles

todo ||--o{ todo: parent-child

@enduml